name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # chạy thủ công

jobs:
  terraform:
    name: 'AWS Infrastructure Deployment'
    runs-on: ubuntu-latest
    
    
    env:
      AWS_REGION: ap-southeast-1 
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      
      - name:  Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0 # Phiên bản khuyến nghị

     
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      
      - name: Run Checkov Scan
        id: checkov
        uses: bridgecrewio/checkov-action@v1
        with:
          directory: . # Quét thư mục hiện tại (nếu các file .tf nằm ở root)
          output_format: cli
          fail_on: true 
          
      # Khởi tạo Terraform
      - name: Terraform Init
        id: init
        run: terraform init

      # Lên kế hoạch triển khai (Plan)
      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -out=tfplan -no-color

      # Bình luận (optional)
      - name: Comment Plan on PR
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            // Trích xuất kết quả Plan
            const planOutput = process.env.PLAN_OUTPUT;
            // Gửi bình luận lên PR
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Terraform Plan Result\n\n\`\`\`\n${planOutput}\n\`\`\`\n:warning: **Review Changes Carefully before Merging!**`
            })
          env:
            PLAN_OUTPUT: ${{ steps.plan.outputs.stdout }}

      # appply triển khai (Chỉ chạy khi merge/push lên branch 'main')
      - name: Terraform Apply
        # Chỉ chạy Apply khi là sự kiện Push và trên branch main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan